buttons:
  mapping:
    key_c: 0
    key_v: 1
    key_e: 2
    key_r: 3
    key_d: 4
    key_f: 5
axes:
  arrows:
    mapping:
      up_down: 0
      left_right: 1
      up_down_inverse: 2
      left_right_inverse: 3
      page_up_down: 4
    scale: [-1.0, 1.0]
