buttons:
  mapping:
    key_w: 0
    key_x: 1
    key_a: 2
    key_z: 3
    key_q: 4
    key_s: 5
axes:
  sticks:
    mapping:
      linear: 0
      angular: 1
      fake: 2
      angular_rear: 3
    scale: [-1.0, 1.0]
deadzone: 0.05
