buttons:
  mapping:
    key_w: 0
    key_x: 1
    key_a: 2
    key_z: 3
    key_q: 4
    key_s: 5
axes:
  sticks:
    mapping:
      up_down: 0
      left_right: 1
      up_down_inverse: 2
      left_right_inverse: 3
    scale: [-1.0, 1.0]
